# Generated by Django 3.0.3 on 2024-01-27 12:11

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    # Esta es la primera migración, estableciendo el esquema inicial de la base de datos.
    initial = True

    # Dependencias de otras migraciones. Vacío indica que no hay dependencias previas.
    dependencies = [
    ]

    # Operaciones de migración para crear modelos en la base de datos.
    operations = [
        # Creación del modelo Barbershop que representa una barbería.
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                # Clave primaria auto-generada para cada barbería.
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Nombre de la barbería, opcional.
                ('Barbershopname', models.CharField(max_length=100, null=True)),
                # Teléfono de contacto de la barbería, opcional.
                ('phone', models.CharField(max_length=100, null=True)),
                # Email de contacto de la barbería, opcional.
                ('email', models.CharField(max_length=100, null=True)),
                # Área o ubicación de la barbería, opcional.
                ('area', models.CharField(max_length=100, null=True)),
                # Servicio ofrecido por la barbería, con opciones predefinidas.
                ('service', models.CharField(choices=[('Solo cortes', 'Solo Cortes'), ('Servicios Completos', 'Servicios Completos')], max_length=100, null=True)),
            ],
        ),
        # Creación del modelo Customer que representa un cliente.
        migrations.CreateModel(
            name='Customer',
            fields=[
                # Clave primaria auto-generada para cada cliente.
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Nombre del cliente, opcional.
                ('name', models.CharField(max_length=100, null=True)),
                # Teléfono de contacto del cliente, opcional.
                ('phone', models.CharField(max_length=100, null=True)),
                # Email de contacto del cliente, opcional.
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        # Creación del modelo Book que representa una reserva.
        migrations.CreateModel(
            name='Book',
            fields=[
                # Clave primaria auto-generada para cada reserva.
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Fecha de creación de la reserva, registrada automáticamente.
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                # Estado de la reserva, con opciones predefinidas.
                ('status', models.CharField(choices=[('Corte de Cabello y Afeitado 10$', 'Corte de Cabello y Afeitado 10$'), ('Corte de Cabello y Recorte 8$', 'Corte de Cabello y Recorte 8$'), ('Corte de Cabello 7$', 'Corte de Cabello 7$')], max_length=200, null=True)),
                # Relación con el modelo Barbershop, se establece a null si la barbería es eliminada.
                ('barbershop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.Barbershop')),
                # Relación con el modelo Customer, se establece a null si el cliente es eliminado.
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.Customer')),
            ],
        ),
    ]
