# Generated by Django 3.0.3 on 2024-01-27 12:32

from django.db import migrations

class Migration(migrations.Migration):
    # Esta migración depende de la migración '0002_book_service', asegurando que las migraciones se apliquen en orden.
    dependencies = [
        ('barbershop', '0002_book_service'),
    ]

    # Define las operaciones a realizar en la base de datos durante la migración.
    operations = [
        # Operación para renombrar un campo en el modelo 'Book'.
        migrations.RenameField(
            # El modelo al que se aplica la operación.
            model_name='book',
            # El nombre actual del campo a renombrar.
            old_name='service',
            # El nuevo nombre que se asignará al campo.
            new_name='time',
        ),
    ]
