# Generated by Django 3.0.3 on 2024-01-27 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    # Dependencias de la migración, incluyendo el modelo de usuario configurable y una migración previa de 'barbershop'.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbershop', '0003_auto_20200228_1232'),
    ]

    # Operaciones a realizar en la base de datos durante la migración.
    operations = [
        # Añade un nuevo campo 'user' al modelo 'Customer'.
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(
                # Permite que el campo sea nulo.
                null=True,
                # Establece la acción de eliminación en cascada. Si el usuario se elimina, el registro del cliente también se eliminará.
                on_delete=django.db.models.deletion.CASCADE,
                # Establece la relación con el modelo de usuario configurado en Django.
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
