# Generated by Django 3.0.3 on 2024-01-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    # Dependencias de la migración, asegurando que se aplique después de la creación del campo 'user' en 'Customer'.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbershop', '0004_customer_user'),
    ]

    # Operaciones de migración para modificar la base de datos.
    operations = [
        # Añade un nuevo campo 'user' al modelo 'Barbershop'.
        migrations.AddField(
            model_name='barbershop',
            name='user',
            field=models.OneToOneField(
                # Permite que el campo sea nulo, indicando que no todas las barberías deben estar vinculadas a un usuario.
                null=True,
                # Establece la acción de eliminación en cascada: si el usuario se elimina, el registro de 'Barbershop' relacionado también se eliminará.
                on_delete=django.db.models.deletion.CASCADE,
                # Establece la relación con el modelo de usuario configurado en Django, permitiendo usar un modelo de usuario personalizado.
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

