# Generated by Django 3.0.3 on 2024-01-27 01:22

from django.db import migrations, models

class Migration(migrations.Migration):
    # Dependencias de la migración, asegurando que se aplica después de la migración que añade el campo 'user' a 'Barbershop'.
    dependencies = [
        ('barbershop', '0005_barbershop_user'),
    ]

    # Operaciones para modificar la base de datos.
    operations = [
        # Añade un nuevo campo 'profile_pic' al modelo 'Customer'.
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(
                # Permite que el campo esté en blanco y sea nulo, ofreciendo flexibilidad.
                blank=True,
                null=True,
                # Define el directorio de subida de las imágenes. Se debe especificar el path.
                upload_to='customer_profiles/',
            ),
        ),
    ]

