# Generated by Django 5.0.1 on 2024-01-25 17:50

from django.db import migrations, models

class Migration(migrations.Migration):
    # Dependencias de la migración, asegurando que se aplica después de añadir el campo de imagen de perfil a 'Customer'.
    dependencies = [
        ('barbershop', '0006_customer_profile_pic'),
    ]

    # Operaciones para modificar la base de datos.
    operations = [
        # Actualiza el campo 'id' de 'Barbershop' a BigAutoField.
        migrations.AlterField(
            model_name='barbershop',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        # Actualiza el campo 'id' de 'Book' a BigAutoField.
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        # Actualiza el campo 'id' de 'Customer' a BigAutoField.
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
    ]
